const bingos=[
// Text only
"Pulls a Maji",
"Sound alert at bathroom break",
"Single digit COTD Div",
"> 10 First round KO in Cup of the Maji",
"Chat asks what Maji is drinking",
"Maji drinks Saft without diluting it first",
"JUST DO IT",
"Storytime",
"COTD V2",
"Maji talks about anime",
"Maji roasts someone",
"COTD Win (in any div)",
"Speaks Norwegian",
"Maji builds a loop",
"Maji makes a weird noise",
"Maji hugs sniff",
"Lvl 5 Hypetrain",
"Maji spills her drink",
"FS Map",
"Ice Map",
"Word lost in translation",
"VC with someone",
"Bad TTS joke",
"TTS donation spam",
"Believers Win",
"Doubters Win",
"Sub bomb (20+)",
"Maji makes a map",
"Maji get's raided",
"Chat is horny",
"Maji falls for a ligma joke",
"Maji Accidentally makes a Kacky map",
"Difficult Author time",
"Risky finish is actually hard",
"Maji fails the risky finish",
"Maji mentions some kind of step-relative",
"Maji mispronounces someones name",
"Caster's Curse get's someone killed",
"Maji snipes someone",
"Clipable moment",
"Maji's map has a cut",

// Non-seasonal emotes
"<img src=\"https://static-cdn.jtvnw.net/emoticons/v2/emotesv2_bcd77a288fa24c90855a34965af39f68/default/light/1.0\" /> Maji Rage",
"<img src=\"https://static-cdn.jtvnw.net/emoticons/v2/emotesv2_b5c66ddbb1cd4aa8b89c372fcbb8ff30/static/light/1.0\" /> Chair gang redeem",
"<img src=\"https://static-cdn.jtvnw.net/emoticons/v2/emotesv2_5b1982e6fb094bd6898a6deedcb0d6d7/default/light/1.0\" /> Maji threatens someone",
"<img src=\"https://static-cdn.jtvnw.net/emoticons/v2/emotesv2_4da6e2bfacf54a6dbce243881f7b53d9/static/light/1.0\" /> Maji focuses",
"<img src=\"https://cdn.betterttv.net/emote/5f1b0186cf6d2144653d2970/1x\" /> banger song",
"<img src=\"https://cdn.betterttv.net/emote/617706061f8ff7628e6afb02/1x\" /> Streamer doesn't know",
"<img src=\"https://cdn.betterttv.net/emote/612464ddaf28e9568649ca10/1x\" /> Gears",
"<img src=\"https://cdn.betterttv.net/emote/59143b496996b360ff9b807c/1x\" /> Opens canned drink",
"Chat spams <img src=\"https://cdn.betterttv.net/emote/60cd2cfb8ed8b373e4216130/1x\" />",
"Chat spams <img src=\"https://cdn.betterttv.net/emote/61942e5e54f3344f8805f103/1x\" />",
"Maji's Map is <img src=\"https://cdn.betterttv.net/emote/611ace7e76ea4e2b9f779ad3/1x\" />",
"Map is <img src=\"https://cdn.betterttv.net/emote/611ace7e76ea4e2b9f779ad3/1x\" />",
"<img src=\"https://cdn.frankerfacez.com/emoticon/418189/1\" /> POLE",
"<img src=\"https://cdn.frankerfacez.com/emoticon/418189/1\" /> TREE",
"<img src=\"https://cdn.frankerfacez.com/emoticon/418189/1\" /> OIL",
"<img src=\"https://cdn.frankerfacez.com/emoticon/457124/1\" /> WICKED",
"Chat is <img src=\"https://cdn.frankerfacez.com/emoticon/243789/1\" />",

// Seasonal emotes
"<img src=\"https://static-cdn.jtvnw.net/emoticons/v2/emotesv2_19cc0f6103d94ea0b0bb27ab270cf991/default/light/1.0\" /> Maji says something sus (Free Space)"
];