const bingos=[
"Wirt talks about his fridge",
"Contact Lens Solution joke",
"Bad Text-to-Speech Joke",
"Text-to-Speech/Donation Spam",
"Wirt turns off Alerts",
"Wirt's Terrible Takes (Shower with socks etc.)",
"<img src=\"https://cdn.betterttv.net/emote/5f1b0186cf6d2144653d2970/1x\" /> banger song",
"Wirt defends anime/weeb music",
"Wirt's cooking",
"Gifted sub bomb (20+)",
"\"And then, X got this run.\"",
"Wirt makes a map",
"<img src=\"https://cdn.betterttv.net/emote/5e7cdc1d6d485d372b29e733/1x\" /> Streamer Doesn't Know",
"Childhood story",
"Micka on Ice",
"Wirt talks about a Future Video or Project",
"Believers Win",
"Doubters Win",
"<img src=\"https://cdn.frankerfacez.com/emoticon/418189/1\" /> OIL",
"<img src=\"https://cdn.frankerfacez.com/emoticon/418189/1\" /> TREE",
"<img src=\"https://cdn.frankerfacez.com/emoticon/418189/1\" /> POLE",
"<img src=\"https://cdn.frankerfacez.com/emoticon/418189/1\" /> COCK",
"Someone mentions the Butter Crisis",
"Norway > Sweden",
"Wirt speaks Norwegian",
"Wirt praises Sweden",
"Wirt gets Raided",
"Wirt gets WR",
"Maji joins VC",
"Scrapie joins VC",
"Marbles on Stream",
"Level 5 Hype Train",
"<img src=\"https://cdn.frankerfacez.com/emoticon/457124/1\" /> WICKED",
"Pulls a Wirtual (Clutch)",
"Pulls a Wirtual (Choke)",
"En Aften Ved Svanefossen",
"Insane TAS Reaction",
"Wirt explains the Red Block (Engine Off)",
"Wirt explains the Blue Block (Cruise Control)",
"Wirt fishes for Primes",
"Turtleneck",
"Wirt mentions Updates",
"Wirt mentions Sigma Grindset",
"Wirt finds a Shortcut",
"Ice in COTD",
"Sus Trophies",
"Someone talks about Gears",
"Someone makes a Riolu joke",
"Storytelling Voice",
"Division 1 COTD",
"Wirt says something sus",
"Maji says something sus",
"<img src=\"https://cdn.frankerfacez.com/emoticon/563443/1\" /> COPIUM",
"Voice crack",
"COTD Win",
"Voice chat with Guest",
"Chat complains about Channel Points",
"Chat is Horny",
"Text-to-Speech compliment",
"<img src=\"https://cdn.betterttv.net/emote/5f24435d713a6144748a91c7/1x\" /> PETTHEMODS",
"Paid in Exposure",
"Mufat joke",
"Wirt argues what \"Pulling a Wirtual\" means",
"Chat is full of Doctors and Experts",
"Not Division 1 in COTD",
"Wirt explains what Speedsliding is",
"Wirt explains what an Iceslide is",
"Wirt explains what a Bugslide/Grass-slide is",
"Map requires/uses a Bugslide",
"Wirt explains what a Nosebug/boost is",
"<img src=\"https://static-cdn.jtvnw.net/emoticons/v2/emotesv2_43cf2536a09a4816b4aecb459b2e593d/default/dark/1.0\" /><br>Wirt raids someone at the end of stream",
"Wirt barely misses a WR",
"Ice map",
"RPG map",
"Fullspeed map",
"Kacky map",
"Trial map",
"Wirt makes a terrible joke",
"Wirt gets roasted",
"The number 69 appears",
"The number 420 appears",
"Wirt gets salty",
"Chat asks when Wirt is gonna get a WR (D13, Bennet Foddy etc.)",
"Chat backseats",
"<img src=\"https://cdn.betterttv.net/emote/5f133c6d6a65270522169b73/1x\" /><br>Stressful hard map",
"<img src=\"https://static-cdn.jtvnw.net/emoticons/v2/emotesv2_94526c089f024b6482f544d11d4bf2ac/default/dark/1.0\" /> Wirt focuses on playing",
"Wirt plays Nations Forever",
"Someone asks how to get medal times on screen",
"Wirt uses a word the wrong way",
"<img src=\"https://cdn.betterttv.net/emote/5ad22a7096065b6c6bddf7f3/1x\" /> Map is WAYTOODANK",
"Very hard author time",
"Someone mentions IKEA",
"Speedcheck",
"Risky finish is actually hard",
"Wirt fails the risky finish",
"<img src=\"https://static-cdn.jtvnw.net/emoticons/v2/emotesv2_5e32ca0cc3fa48618d7e044bcb2f8e29/default/dark/1.0\" /> Clippable moment",
"<img src=\"https://cdn.betterttv.net/emote/6083732039b5010444d051e8/1x\"><br>Streamer is late",
"Wirtual scams someone",
"Tristan shows up"
];
